### ISSUE TITLE
500 Error when Discourse PM is sent.

### ISSUE THREAD

**Issue by FerrariFlunker** [merefield/discourse-discord-bot#5]
![image](https://user-images.githubusercontent.com/85372028/155898085-53227e9a-01b0-40b5-9314-e75597a3099c.png)

We've been getting an error that we've tracked down to the discord bot plugin.  The above image shows the inspect element error, but any user who sends a PM also gets a "500 Error" visual when their PM is sent.  The PM is still sent successfully, but this error makes it seem otherwise.  After disabling the plugin, the issue no longer exists. 

I'm pretty sure the issue is coming from /lib/discourse_event_handlers.rb.  I'm assuming that a PM is triggering the post_created DiscourseEvent which makes it try to access the post's category via posted_category = post.topic.category.id, which causes the error.

I hope this helps and I hope this can be resolved soon.  Thanks

**Comment by merefield** [comment]
Fix deployed: https://github.com/merefield/discourse-discord-bot/commit/82b210980c2e0ef17a1ea6d310442c62b3454973

Please confirm I can close.

**Comment by FerrariFlunker** [comment]
Thank you for fixing this!  Unfortunately we're not able to confirm it's fixed on our site (due to plugin changes), but I'm good with closing this regardless.
